### ISSUE TITLE
Failure when special characters are present in password

### ISSUE THREAD

**Issue by feynmanliang** [appany/helm-oci-chart-releaser#14]
**Describe the bug**

When the OCI password contains a ")", this action fails with "bash: syntax error near unexpected token `)'".

Root cause is https://github.com/appany/helm-oci-chart-releaser/blob/main/action.yaml#L45 does not escape its input.

Current workaround is to escape manually in the yaml

```yaml
registry_password: "\"mypass)\""
```

Would be nice if escaping was handled in the action instead.

**Comment by sergeyshaykhullin** [comment]
@feynmanliang PRs are welcome!
