### ISSUE TITLE
Broken with Helm 3.7.0 Release

### ISSUE THREAD

**Issue by sbckr** [appany/helm-oci-chart-releaser#4]
Hi, 
first of all, thank you for providing this Action.

**Describe the bug**
With [Helm Release 3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0) the `helm chart` command was removed or partially replaced by other commands:

># Notable Changes
>A few major changes were made to the experimental OCI feature:
>- `helm chart export` has been removed
>- `helm chart list` has been removed
>- `helm chart pull` has been replaced with `helm pull`
>- `helm chart push` has been replaced with `helm push`
>- `helm chart remove` has been removed
>- `helm chart save` has been replaced with `helm package`

Since GitHub is already shipping Helm 3.7.0 with their latest [Ubuntu 20.04 virtual-environment](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210919.1), running the `helm-oci-chart-releaser` fails with the following error:

```bash
Error: unknown command "chart" for "helm"
Run 'helm --help' for usage.
Error: Process completed with exit code 1.
```

**To Reproduce**
1. Define GitHub workflow using  GitHub virtual-environment `ubuntu-20.04`
2. Define `appany/helm-oci-chart-releaser@v0.2.0` as a wotkflow step

Or checkout one of our repository's workflow (just default stuff):
- [Action Log](https://github.com/carbynestack/ephemeral/runs/3731725362?check_suite_focus=true)
- [Workflow definition](https://github.com/carbynestack/ephemeral/blob/master/.github/workflows/publish-and-release.yaml#L139)

**Expected behavior**
The action should complete (upload the chart) as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/43000614/135217243-bce87a3e-c9d7-4570-a7b9-dbbf37f8b89a.png)

**Comment by sergeyshaykhullin** [comment]
@sbckr Thanks for your detailed report!

Seems like helm stabilized oci apis and if `@v0.3.0` version will work as expected i will release `@v1`

**Comment by sbckr** [comment]
@sergeyshaykhullin Thank you for your quick response! 🏎️ 

I'll adapt our pipeline to use release [v0.3.0](https://github.com/appany/helm-oci-chart-releaser/releases/tag/v0.3.0) and provide further feedback once available.

**Comment by sergeyshaykhullin** [comment]
@sbckr Action is migrated to helm 3.7.0, tested with ghcr. But some cd tools may not already adopted new helm oci format.

I will not release `@v1` as helm oci support is still experimental

**Comment by sbckr** [comment]
@sergeyshaykhullin #5 fixed the issue for us. Thanks again!

**Comment by rowi1de** [comment]
Hey @sergeyshaykhullin did you experience any issue with 0.4.0 so far? 
https://github.com/appany/helm-oci-chart-releaser/issues/7
