### ISSUE TITLE
Github Actions set-output command is deprecated

### ISSUE THREAD

**Issue by shay-ul** [appany/helm-oci-chart-releaser#6]
**Describe the bug**
When running this action, github action prints the following warning:
_The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/_

**To Reproduce**
1. Run the action inside a Github Action workflow and observe the warnings

**Comment by shay-ul** [comment]
hey @sergeyshaykhullin , looks like this project is no longer maintaned? Should I look for replacement or can you have a look?
Thanks

**Comment by sergeyshaykhullin** [comment]
This project is actively maintained, but it is pretty simple and no changes required for a long time

**Comment by rowi1de** [comment]
There are some more GitHub Action deprecations coming soon https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by sergeyshaykhullin** [comment]
This is not a node js action
